# My global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:


# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:


# A scrape configuration containing exactly one endpoint to scrape:
# scraped from this config.
scrape_configs:
  - job_name: 'springboot-grafana-practice'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8800']
